# Generated by Django 3.0.6 on 2020-05-13 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
