apiVersion: v1
kind: Service
metadata:
  name: letter-server-svc-name # modify here
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30123 # modify here
  selector:
    trainee: NAME # modify here
